@base_url=3000-danielsouza-adsbackend2-hxp4qteamnf.ws-us54.gitpod.io

GET https://{{base_url}} HTTP/1.1

HTTP/1.1 200  - OK
content-length: 11
content-type: text/html; charset=utf-8
date: Mon, 18 Jul 2022 20:17:13 GMT
etag: W/"b-d04Mc17dZHxRTm1oXSWe3mBlnRc"
x-powered-by: Express
connection: close